version: '3.9'

services:
#  java_app:
#    container_name: java_app
#    image: todoapp/java_app:1.0.0
#    build: .
#    ports:
#      - 8080:8080
#    environment:
#      - DATABASE_URL=jdbc:postgresql://localhost:5432/postgres
#      - DATABASE_USERNAME=root
#      - DATABASE_PASSWORD=mateusz
#    depends_on:
#      - java_db

  java_db:
    container_name: java_db
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: mateusz
      POSTGRES_DB: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: {}